title: 'Product Field'
key: 'product_default'
position: 'acf_after_title'
hide_on_screen: []
location:
  -
    -
      param: 'post_type'
      operator: '=='
      value: 'product'
fields:
  flex_content:
    label: Flex Content
    type: "clone"
    display: "seamless"
    prefix_label: false
    prefix_name: false
    clone:
      - "flex_content"